### ISSUE TITLE
"BorshIoError":"Unknown" on lecture_3

### ISSUE THREAD

**Issue by johhnsmmith198** [solana-developers/solana-bootcamp-lectures#3]
I tried deploying the 2 program and running the js code (after updating the program ids).
```
➜  js git:(master) ✗ node index.js
Tracker Program 5TGVmbsK1C9zCtoMA23pwLk2w4YSuiKgMyrccvNYqHVE
Counter Program Gjf9qSDhygUCLR8kyXRzRL9EpPtBU8URjpjqfaXMRZXL
Requesting Airdrop of 1 SOL...
Airdrop received
Generating new counter address
    -> No tracker account found. Creating new tracker account
Incrementing counter
Error: Transaction 4eVxfZR236nR2UD5VJ1msLTDJGXRyny2phb3vdQ3PAxBnV5QDnXQv1u2sWvq4Ku5942fcYRnLRdAzg1gzHm2i9ww failed ({"err":{"InstructionError":[1,{"BorshIoError":"Unknown"}]}})
    at sendAndConfirmTransaction (/home/pc/Documents/funspace/crypto-world/lab/solanaworkspace/solana-bootcamp-lectures/lecture_3/js/node_modules/@solana/web3.js/lib/index.cjs.js:2965:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/pc/Documents/funspace/crypto-world/lab/solanaworkspace/solana-bootcamp-lectures/lecture_3/js/index.js:160:14)
```
log
```
Transaction executed in slot 1548:
  Signature: 4eVxfZR236nR2UD5VJ1msLTDJGXRyny2phb3vdQ3PAxBnV5QDnXQv1u2sWvq4Ku5942fcYRnLRdAzg1gzHm2i9ww
  Status: Error processing Instruction 1: Failed to serialize or deserialize account data: Unknown
  Log Messages:
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program 5TGVmbsK1C9zCtoMA23pwLk2w4YSuiKgMyrccvNYqHVE invoke [1]
    Program log: process_instruction: 5TGVmbsK1C9zCtoMA23pwLk2w4YSuiKgMyrccvNYqHVE: 5 accounts, data=[0]
    Program log: Instruction: Increment
    Program 5TGVmbsK1C9zCtoMA23pwLk2w4YSuiKgMyrccvNYqHVE consumed 15070 of 200000 compute units
    Program 5TGVmbsK1C9zCtoMA23pwLk2w4YSuiKgMyrccvNYqHVE failed: Failed to serialize or deserialize account data: Unknown
```

**Comment by johhnsmmith198** [comment]
I mixed up the 2 program ids in my javascript
